server:
  port: 8080
  url: http://localhost:8081

logging:
  level:
    root: WARN
    ru: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testSpring
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver